# Stage 1: Build Frontend
FROM node:18-slim AS frontend
WORKDIR /app/frontend

COPY public/WebsiteBusinessCard/package*.json ./
RUN npm install

COPY public/WebsiteBusinessCard/ ./
RUN npm run build

FROM nginx:alpine

COPY --from=frontend /app/frontend/build /usr/share/nginx/html
COPY --from=frontend /app/frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]