# Stage 1: Build Backend
FROM python:3.9 AS backend
WORKDIR /app/backend
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/backend

RUN python manage.py collectstatic --noinput


EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "portfolio.wsgi:application"]
