# Generated by Django 4.2.16 on 2024-10-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardAndSoftSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(max_length=50, verbose_name='Тип навыка')),
                ('skill_name', models.CharField(max_length=50, verbose_name='Название')),
                ('skill_img', models.ImageField(null=True, upload_to='images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
    ]
