# Generated by Django 4.2.16 on 2024-11-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_hardandsoftskills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainskills',
            options={'verbose_name': 'Навык на главной', 'verbose_name_plural': 'Навыки на главной'},
        ),
        migrations.AlterField(
            model_name='hardandsoftskills',
            name='skill_img',
            field=models.ImageField(null=True, upload_to='skills', verbose_name='Изображение'),
        ),
    ]
